### ISSUE TITLE
Python 3.8 removed time.clock()

### ISSUE THREAD

**Issue by propfeds** [RandomOrg/JSON-RPC-Python#6]
The service no longer works because of it,

**Comment by RandomOrgDev** [comment]
Hello, 
The most recent updates to the repository (066715c5cebc4862e3facc23ddbd400c8e7650a1 and 414af93dc7793e4c3d5a0d24c2fd75756a2af90b) also cover support for Python 3.8+. Additionally, new methods included in Release 2 and 3 of the RANDOM.ORG JSON-RPC API have also been added (see [R2](https://api.random.org/json-rpc/2/fundamentals) and [R3](https://api.random.org/json-rpc/3/fundamentals)). These updates are also available for the package on [PyPI](https://pypi.org/project/rdoclient/1.3).
As such, this issue should now have been resolved. 
If there are any other problems, please do let us know. 
Thank you for your interest in this library!

**Comment by propfeds** [comment]
How should I approach the new version then, even if it's just a simple `generate_integers()`? The methods I had been using still use `time.clock()`.

**Comment by RandomOrgDev** [comment]
The updated version uses time.clock() if no error is thrown (i.e. for Python < 3.8) and time.process_time() otherwise (i.e. for Python > 3.8). So your call to `generate_integers()`, as an example, does not need to be changed as long as the rdoclient package has been updated (minimum for Python 3 support: https://github.com/RandomOrg/JSON-RPC-Python/commit/066715c5cebc4862e3facc23ddbd400c8e7650a1 or PyPI [rdoclient version 1.2](https://pypi.org/project/rdoclient/1.2/)). Does this help at all?

**Comment by propfeds** [comment]
I have rdoclient 1.3 and Python 3.8.2, and I tried it but still reports time.clock() is missing.

Edit: Turns out my project has conflicts with another fork of rdo. Thank you, my problem is solved.

**Comment by RandomOrgDev** [comment]
Perfect, glad to hear it has been sorted. 

There is also a newer version of the rdoclient ([1.3.1](https://pypi.org/project/rdoclient/1.3.1/)) available, which fixes an issue with the "base" parameter in integer methods, as well as an error in the "create_x_cache" methods. So if you use any of those parameters/methods, the update might be helpful, too. 

Thank you.
